# Generated by Django 4.0.5 on 2022-07-13 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_friendrequest_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_user_recipient_id', to='polls.user'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_user_sender_id', to='polls.user'),
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user_sender_id', to='polls.user')),
                ('violator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user_violator_id', to='polls.user')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_question_sender_id', to='polls.user')),
                ('violator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_question_violator_id', to='polls.question')),
            ],
        ),
    ]
