# Generated by Django 4.0.5 on 2022-07-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_punishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(None, 'Outro'), (True, 'Masculino'), (False, 'Feminino')], max_length=30),
        ),
    ]
