# Generated by Django 4.0.5 on 2022-07-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[(None, 'Outro'), (True, 'Masculino'), (False, 'Feminino')], null=True),
        ),
    ]
